blank_issues_enabled: false
contact_links:
  - name: Guilded Server
    url: https://guilded.gg/hellorein
    about: The official Guilded server for Hoshii is the right place for library-related discussion.
