name: Question
description: Struggling with something? Post your question here
labels:
  - "question"
body:
  - type: markdown
    attributes:
      value: |
        # Asking a Question

        Before posting your question, please consider to:

        - Check whether the question you are about to submit has already been posted or not.
        - You may always use our official [Guilded Server](https://guilded.gg/hoshii) to ask general questions.

        **Note:** We highly recommend to use the official [Guilded Server](https://guilded.gg/hoshii) for questions-related. If your question leads into a bug or an issue, feel free to proceed submitting one.

  - type: textarea
    attributes:
      label: Question
      description: What question would you want to ask?
      placeholder: I am confused. How can I...??
    validations:
      required: true
