name: Question
description: Struggling with something? Post your question here
labels:
  - "question"
body:
  - type: markdown
    attributes:
      value: |
        # Asking a Question

        Before posting your question, please consider to:

        - Check whether the question you are about to submit has already been posted or not.
        - You may always use our official [Guilded Server](https://guilded.gg/hellorein) to ask any multiple questions.

  - type: textarea
    attributes:
      label: Question
      description: What question would you want to ask?
      placeholder: I am confused. How can I...??
    validations:
      required: true
